# Generated by Django 5.2 on 2025-05-22 11:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанри',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_books_found', models.IntegerField(default=0)),
                ('books_created', models.IntegerField(default=0)),
                ('books_updated', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Виконується'), ('completed', 'Завершено'), ('failed', 'Помилка'), ('interrupted', 'Перервано')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Лог скрапінгу',
                'verbose_name_plural': 'Логи скрапінгу',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('publication_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2030)], verbose_name='Рік публікації')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ціна')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наявності')),
                ('availability', models.CharField(blank=True, max_length=100, verbose_name='Наявність')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='URL джерела')),
                ('last_scraped', models.DateTimeField(blank=True, null=True, verbose_name='Останнє оновлення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='scraper_boo_title_102b7c_idx'), models.Index(fields=['author'], name='scraper_boo_author_37f491_idx'), models.Index(fields=['genre'], name='scraper_boo_genre_i_37dfbe_idx'), models.Index(fields=['publication_year'], name='scraper_boo_publica_7e4bcf_idx'), models.Index(fields=['rating'], name='scraper_boo_rating_ba5148_idx')],
                'unique_together': {('title', 'author')},
            },
        ),
    ]
