# Generated by Django 5.2 on 2025-05-29 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_book_options_alter_genre_options_book_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapinglog',
            options={'ordering': ['-started_at'], 'verbose_name': 'Scraping log', 'verbose_name_plural': 'Scraping logs'},
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='scraper_boo_author_37f491_idx',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='scraper_boo_publica_7e4bcf_idx',
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_year',
        ),
    ]
