# Generated by Django 5.2 on 2025-05-30 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_scrapinglog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.book', verbose_name='Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Favorite book',
                'verbose_name_plural': 'Favorite books',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='scraper_fav_user_id_9126cd_idx'), models.Index(fields=['book'], name='scraper_fav_book_id_6a529c_idx')],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
